### PR TITLE
Fix missing increment of in_flight in acquire_timeout

### PR DESCRIPTION
**Pull request by jkylling**

### CODE REVIEW

**Comment by jkylling** [comment]
@ThomWright thank you for this very interesting library! There seems to be a bug in `acquire_timeout` in that we forget to increment the number of in flight tokens. Perhaps the increment should be moved to happen within `Token::new`?

**Comment by ThomWright** [comment]
Good spot!

> Perhaps the increment should be moved to happen within Token::new?

This seems like a good idea, especially since the decrement occurs in the `Token::drop`. Would you like to make that change? I'll be happy to merge it.

**Comment by jkylling** [comment]
> Good spot!
> 
> > Perhaps the increment should be moved to happen within Token::new?
> 
> This seems like a good idea, especially since the decrement occurs in the `Token::drop`. Would you like to make that change? I'll be happy to merge it.

Yes, updated now. Please have a look.

**Review by ThomWright — APPROVED** [review]
Thank you!

**Pull request merged**
